In [1]:
# Importing Librarires that already installed on terminal with pip:

import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

# q1 and q2 answers:

In [11]:
# Version check:
print(np.__version__)
print(pd.__version__)

1.23.2
1.4.3


In [12]:
# Download the data:

!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-08-30 14:38:58--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1,4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1,41M  4,88MB/s    in 0,3s    

2022-08-30 14:38:59 (4,88 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [53]:
df = pd.read_csv('data.csv')

In [54]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [55]:
# Extra:
df.columns = df.columns.str.replace(' ','_')
df = df.round(2)

# Question 3: What's the average price of BMW cars in the dataset?

In [56]:
df[df['Make'] == 'BMW']['MSRP'].mean().round(2)

61546.76

# Question 4: Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [57]:
df.loc[df['Year']>=2015]['Engine_HP'].isnull().sum()

51

# Question 5: Calculate the average "Engine HP" in the dataset.Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.Now, calcualte the average of "Engine HP" again. Has it changed?

In [58]:
# Avg 'Engine hp':
df['Engine_HP'].mean().round(2)

249.39

In [59]:
df['Engine_HP'] = df['Engine_HP'].fillna(df['Engine_HP'].mean())
df['Engine_HP'].isnull().sum()

0

In [62]:
df['Engine_HP'].mean().round(2)

249.39

# Question 6 Select all the "Rolls-Royce" cars from the dataset.Select only columns "Engine HP", "Engine Cylinders", "highway MPG".Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).Get the underlying NumPy array. Let's call it X.Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.Invert XTX.What's the sum of all the elements of the result?Hint: if the result is negative, re-read the task one more time

In [70]:
df_new = df[df['Make']=='Rolls-Royce'].filter(['Engine_HP','Engine_Cylinders','highway_MPG'],axis=1)

In [71]:
# Dropping duplicates:

df_new = df_new.drop_duplicates()

In [73]:
df_new = df_new.reset_index(drop='firt')

In [106]:
df_new = df_new.astype('int')

In [115]:
df_new

Engine_HP  Engine_Cylinders  highway_MPG
0        325                 8           15
1        563                12           19
2        563                12           21
3        563                12           20
4        322                12           15
5        453                12           19
6        624                12           21

In [108]:
#creating array:
X = df_new.values

In [109]:
X

array([[325,   8,  15],
       [563,  12,  19],
       [563,  12,  21],
       [563,  12,  20],
       [322,  12,  15],
       [453,  12,  19],
       [624,  12,  21]])

In [110]:
# Transpose
Y = X.T
Y

array([[325, 563, 563, 563, 322, 453, 624],
       [  8,  12,  12,  12,  12,  12,  12],
       [ 15,  19,  21,  20,  15,  19,  21]])

In [123]:
Y

array([[325, 563, 563, 563, 322, 453, 624],
       [  8,  12,  12,  12,  12,  12,  12],
       [ 15,  19,  21,  20,  15,  19,  21]])

In [120]:
XTX = X.T.dot(X)

In [122]:
# Inverse of XTX:
inv_XTX = np.linalg.inv(XTX)
inv_XTX.sum()

0.032212320677486125

# Questions 7: Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w. What's the value of the first element of w?.

In [126]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

w = inv_XTX.dot(Y).dot(y)

In [127]:
w[0]

0.19989598183188972