In [1]:
import numpy as np

# Creating arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [5]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi - dimensional arrays

In [6]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Randomly generated arrays

In [10]:
np.random.seed(10) #to get same result we fixed seed number(it depends on numpy version and operating system)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [12]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operatioans

In [13]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [14]:
a + 1

array([1, 2, 3, 4, 5])

# Comparison operations

In [15]:
a

array([0, 1, 2, 3, 4])

In [17]:
a >= 3

array([False, False, False,  True,  True])

In [25]:
b = np.random.rand(1,5)

In [28]:
b

array([[0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515]])

In [27]:
a > b

array([[False,  True,  True,  True,  True]])

# 1- Multiplication of Vectors

In [34]:
u = np.array([1,2,3])
v = np.array([4,5,6])

In [35]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
        
    return result   

In [36]:
vector_vector_multiplication(u,v)

32.0

In [38]:
# It is possible to do directly with 'dot' 
u.dot(v)

32

# 2- Matrix-vector multiplication

In [40]:
U = np.array([[1,4,7],
            [2,3,0],
            [5,1,9]])

In [41]:
U

array([[1, 4, 7],
       [2, 3, 0],
       [5, 1, 9]])

In [44]:
U.shape

(3, 3)

In [47]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    
    return result

In [48]:
matrix_vector_multiplication(U,v)

array([66., 23., 79.])